/// @description Free surfaces
if(surface_exists(playerInvSurf))
{
    surface_free(playerInvSurf);
}
if(surface_exists(playerGlowSurf))
{
    surface_free(playerGlowSurf);
}
if(surface_exists(playerGlowSurf2))
{
    surface_free(playerGlowSurf2);
}
if(surface_exists(pauseSurf))
{
    surface_free(pauseSurf);
}
if(surface_exists(mapSurf))
{
    surface_free(mapSurf);
}